### ISSUE TITLE
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project ocr-tess4j-example: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

### ISSUE THREAD

**Issue by ShilpaRane** [compomics/mascotdatfile#13]
I want to use OCR in my project.  I used Tess4j library , and it shows this error .

--- exec-maven-plugin:1.2.1:exec (default-cli) @ ocr-tess4j-example ---
Exception in thread "main" java.lang.NoSuchFieldError: RESOURCE_PREFIX
    at net.sourceforge.tess4j.util.LoadLibs.<clinit>(LoadLibs.java:57)
    at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42)
    at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:368)
    at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:281)
    at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:213)
    at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:197)
## BUILD FAILURE

Total time: 2.140s
Finished at: Sat Jul 16 11:37:48 IST 2016
## Final Memory: 8M/100M

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project ocr-tess4j-example: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by hbarsnes** [comment]
Sorry for the late reply. But I cannot see how this issue is related to MascotDatfile? Are you sure you set up the issue for the correct GitHub project?

Best regards,
Harald
